'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetOrderDetails", ReplyAction:="http://tempuri.org/IService1/GetOrderDetailsResponse")>  _
        Function GetOrderDetails() As OMS.Business.Order()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetOrderDetails", ReplyAction:="http://tempuri.org/IService1/GetOrderDetailsResponse")>  _
        Function GetOrderDetailsAsync() As System.Threading.Tasks.Task(Of OMS.Business.Order())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetOrderSummary", ReplyAction:="http://tempuri.org/IService1/GetOrderSummaryResponse")>  _
        Function GetOrderSummary(ByVal orderId As Integer) As OMS.Business.Order
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetOrderSummary", ReplyAction:="http://tempuri.org/IService1/GetOrderSummaryResponse")>  _
        Function GetOrderSummaryAsync(ByVal orderId As Integer) As System.Threading.Tasks.Task(Of OMS.Business.Order)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetVendors", ReplyAction:="http://tempuri.org/IService1/GetVendorsResponse")>  _
        Function GetVendors() As OMS.Business.Vendor()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetVendors", ReplyAction:="http://tempuri.org/IService1/GetVendorsResponse")>  _
        Function GetVendorsAsync() As System.Threading.Tasks.Task(Of OMS.Business.Vendor())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/AddOrderDetails", ReplyAction:="http://tempuri.org/IService1/AddOrderDetailsResponse")>  _
        Sub AddOrderDetails(ByVal order As OMS.Business.Order)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/AddOrderDetails", ReplyAction:="http://tempuri.org/IService1/AddOrderDetailsResponse")>  _
        Function AddOrderDetailsAsync(ByVal order As OMS.Business.Order) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/DeleteOrder", ReplyAction:="http://tempuri.org/IService1/DeleteOrderResponse")>  _
        Sub DeleteOrder(ByVal orderId As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/DeleteOrder", ReplyAction:="http://tempuri.org/IService1/DeleteOrderResponse")>  _
        Function DeleteOrderAsync(ByVal orderId As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/DeleteSelectedOrderInList", ReplyAction:="http://tempuri.org/IService1/DeleteSelectedOrderInListResponse")>  _
        Sub DeleteSelectedOrderInList(ByVal orderIdsList() As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/DeleteSelectedOrderInList", ReplyAction:="http://tempuri.org/IService1/DeleteSelectedOrderInListResponse")>  _
        Function DeleteSelectedOrderInListAsync(ByVal orderIdsList() As Integer) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceReference1.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IService1)
        Implements ServiceReference1.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetOrderDetails() As OMS.Business.Order() Implements ServiceReference1.IService1.GetOrderDetails
            Return MyBase.Channel.GetOrderDetails
        End Function
        
        Public Function GetOrderDetailsAsync() As System.Threading.Tasks.Task(Of OMS.Business.Order()) Implements ServiceReference1.IService1.GetOrderDetailsAsync
            Return MyBase.Channel.GetOrderDetailsAsync
        End Function
        
        Public Function GetOrderSummary(ByVal orderId As Integer) As OMS.Business.Order Implements ServiceReference1.IService1.GetOrderSummary
            Return MyBase.Channel.GetOrderSummary(orderId)
        End Function
        
        Public Function GetOrderSummaryAsync(ByVal orderId As Integer) As System.Threading.Tasks.Task(Of OMS.Business.Order) Implements ServiceReference1.IService1.GetOrderSummaryAsync
            Return MyBase.Channel.GetOrderSummaryAsync(orderId)
        End Function
        
        Public Function GetVendors() As OMS.Business.Vendor() Implements ServiceReference1.IService1.GetVendors
            Return MyBase.Channel.GetVendors
        End Function
        
        Public Function GetVendorsAsync() As System.Threading.Tasks.Task(Of OMS.Business.Vendor()) Implements ServiceReference1.IService1.GetVendorsAsync
            Return MyBase.Channel.GetVendorsAsync
        End Function
        
        Public Sub AddOrderDetails(ByVal order As OMS.Business.Order) Implements ServiceReference1.IService1.AddOrderDetails
            MyBase.Channel.AddOrderDetails(order)
        End Sub
        
        Public Function AddOrderDetailsAsync(ByVal order As OMS.Business.Order) As System.Threading.Tasks.Task Implements ServiceReference1.IService1.AddOrderDetailsAsync
            Return MyBase.Channel.AddOrderDetailsAsync(order)
        End Function
        
        Public Sub DeleteOrder(ByVal orderId As Integer) Implements ServiceReference1.IService1.DeleteOrder
            MyBase.Channel.DeleteOrder(orderId)
        End Sub
        
        Public Function DeleteOrderAsync(ByVal orderId As Integer) As System.Threading.Tasks.Task Implements ServiceReference1.IService1.DeleteOrderAsync
            Return MyBase.Channel.DeleteOrderAsync(orderId)
        End Function
        
        Public Sub DeleteSelectedOrderInList(ByVal orderIdsList() As Integer) Implements ServiceReference1.IService1.DeleteSelectedOrderInList
            MyBase.Channel.DeleteSelectedOrderInList(orderIdsList)
        End Sub
        
        Public Function DeleteSelectedOrderInListAsync(ByVal orderIdsList() As Integer) As System.Threading.Tasks.Task Implements ServiceReference1.IService1.DeleteSelectedOrderInListAsync
            Return MyBase.Channel.DeleteSelectedOrderInListAsync(orderIdsList)
        End Function
    End Class
End Namespace
